# Generated by Django 4.2.10 on 2024-02-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MicrophoneBedPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microphone_id', models.IntegerField(unique=True)),
                ('bed_id', models.CharField(max_length=100)),
                ('patient_id', models.CharField(max_length=100)),
            ],
        ),
    ]
