# Generated by Django 4.2.10 on 2024-02-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='microphonebedpatient',
            name='practitioner_id',
            field=models.CharField(default='b292f7a7-0adc-40db-bb76-6245b8411fda', max_length=100),
            preserve_default=False,
        ),
    ]
