# Generated by Django 4.2.10 on 2024-03-08 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_requests', '0002_microphonebedpatient_practitioner_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedAudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('processed_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
